/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  mehmetparlak
 * Created: 24-Apr-2017
 */


CREATE TABLE SYSTEMUSERGROUP (
    ID BIGINT NOT NULL,
    USERNAME varchar(100) NOT NULL,
    GROUPNAME varchar(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE SYSTEMUSER (
    ID BIGINT NOT NULL,
    USERNAME varchar(100) NOT NULL UNIQUE,
    USERPASSWORD varchar(100) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CUSTOMER (
    CUSTOMER_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    FIRSTNAME varchar(100) NOT NULL,
    LASTNAME varchar(100) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    BALANCE DOUBLE NOT NULL,
    CURRENCY varchar(1) NOT NULL,
    USERID BIGINT,
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (USERID) REFERENCES SYSTEMUSER(ID)
);

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    SENDER_ID BIGINT NOT NULL,
    RECEIVER_ID BIGINT NOT NULL,
    AMOUNT DOUBLE NOT NULL,
    TDATE VARCHAR(50) NOT NULL,
    STATUS varchar(1) NOT NULL,
    CURRENCY varchar(3) NOT NULL,
    PRIMARY KEY (TRANSACTION_ID)
);

ALTER TABLE CUSTOMER ALTER COLUMN BALANCE SET DATA TYPE DOUBLE;
